name: Release

# secrets setup:
# - NODE_AUTH_TOKEN: ${{secrets.npm_token}}
# - GITHUB_TOKEN (inherent in the CI and no need to set up, used by standalone.js + gh releaser)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-before-publish:
    uses: ./.github/workflows/ci.yml
  publish:
    needs: build-before-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm run hygen:build -- init self # smoke test the built bundle
      - run: npm publish # add the package to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - run: npm run standalone # creates binaries
      - name: Github Release # adds the binaries to github release
        uses: softprops/action-gh-release@v2
        with:
          files: 'standalone/*'
      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-path: hygen.rb
          homebrew-tap: jondot/homebrew-tap
          download-url: 'https://github.com/jondot/hygen/releases/download/${{ steps.extract-version.outputs.tag-name }}/hygen.macos.${{ steps.extract-version.outputs.tag-name }}.tar.gz'
          commit-message: updating formula for Hygen
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
